# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-codex-bridge" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "herdr-self"], chdir: "."
    end
  end

  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "6569d1e70e5e751736f73f195777cf0e0d710676bce583c44007de6affed9863"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb1262a4b51372df3508695df76a530e6905494e211e877e0572833371cd44b4"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "832fe39dbaddf98c154c8181d0f2b9d4641a227824cd2f7e3acade446ececb4a"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b49b39d0ce37aaa7f5cc821991e34eb685fcdf4866fe3c7b2062302ed231940b"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "herdr-codex-bridge"
  desc "Native Herdr pane identity for centralized Codex app-server sessions"
  homepage "https://github.com/ardasevinc/herdr-codex-bridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdr-self"

  # No zap stanza required
end
