# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-codex-bridge" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "527714b05e22de4d5559cd5560a7bd320a49ab02f278a3333e124e9805c5cc1d"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f2794de63c73ed841c788b864b569fb291ed764c78dabb9965a607a813df6bf"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "85c8224ed952c0c1df6a6068fcca92f55d948b0db93aa77d332fca2ed69ce22a"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec18a8b7a54a9ed6f6b4faee0eb1d039fcac77ae4d7acb110473ff5e66c352ce"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "herdr-codex-bridge"
  desc "Native Herdr pane identity for centralized Codex app-server sessions"
  homepage "https://github.com/ardasevinc/herdr-codex-bridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdr-self"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/herdr-self"]
    end
  end

  # No zap stanza required
end
