# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-codex-bridge" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "herdr-self"], chdir: "."
    end
  end

  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "69d8729d3a61e12c6c20cdad0adf3950551ff5f7df48eb694311023274ade56b"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b770068b22dcf22e8c28edeb0fe2acccb1a148c3477c0f30154f6e994dc98bff"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "060aa2909a4e0dbc55734e23923d991cffe702abf9009c9e1a50adee7851402e"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de24b9769a0c1fb3dbd53899dd5a5200d8d6f66c5c572a26c85f54fd68a7c84c"
      url "https://github.com/ardasevinc/herdr-codex-bridge/releases/download/v#{version}/herdr-codex-bridge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "herdr-codex-bridge"
  desc "Native Herdr pane identity for centralized Codex app-server sessions"
  homepage "https://github.com/ardasevinc/herdr-codex-bridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdr-self"

  # No zap stanza required
end
