# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nb < Formula
  desc "An agent-first NetBird management CLI"
  homepage "https://github.com/ardasevinc/netbird-cli"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.1/nb_1.1.1_darwin_amd64.tar.gz"
      sha256 "5541528ec58687d7cd8334d4901ee06e615b4630a280361e2b9d645724eea15d"

      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.1/nb_1.1.1_darwin_arm64.tar.gz"
      sha256 "86b92d54b574e82acce4d35bd2e211fe5e92f04c2203261e3b38001a4047604e"

      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.1/nb_1.1.1_linux_amd64.tar.gz"
      sha256 "166633dcaf14f7a215ee07543303303f8d311a2685207a9b1e7ad98682fb2eb6"
      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.1/nb_1.1.1_linux_arm64.tar.gz"
      sha256 "ca58e1478b7be3fe51e2e1e81713a4da1e1d44e9c470c4a7f32d4cfca73f11c7"
      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  test do
    system "#{bin}/nb", "version"
  end
end
