# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nb < Formula
  desc "An agent-first NetBird management CLI"
  homepage "https://github.com/ardasevinc/netbird-cli"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.0.0/nb_1.0.0_darwin_amd64.tar.gz"
      sha256 "ecfac16c0d4d7fb879d2dea59aedd43bb25603f359c9403b5d12838fd54a765f"

      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.0.0/nb_1.0.0_darwin_arm64.tar.gz"
      sha256 "5265314cd98bbdc8f522fd1a45faed0ba96104d4260b22f0f4a9dcc573f57c1a"

      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.0.0/nb_1.0.0_linux_amd64.tar.gz"
      sha256 "6b43ef9e80c13bdf1905e98074ada6ea5347b3d67030cbbdcdda247ce115fc6d"
      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.0.0/nb_1.0.0_linux_arm64.tar.gz"
      sha256 "a294561b2d0fdbd2ff73607ceea709ed0e7b481559a4240ed6b902d07e6a2a43"
      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  test do
    system "#{bin}/nb", "version"
  end
end
