# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nb < Formula
  desc "An agent-first NetBird management CLI"
  homepage "https://github.com/ardasevinc/netbird-cli"
  version "1.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.3/nb_1.1.3_darwin_amd64.tar.gz"
      sha256 "8eed1bead960283b6267bc09945474d27b7956828e2633e54d0bf7fa697dd2e6"

      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.3/nb_1.1.3_darwin_arm64.tar.gz"
      sha256 "cf47222923874b243eb43dfe74ca41283d5d3ec5bb2e43e31bc48ae4a6418c56"

      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.3/nb_1.1.3_linux_amd64.tar.gz"
      sha256 "2f44e6599ffaddcbd272f174a50f59ff9c666304e100bd651af6967404ab4619"
      define_method(:install) do
        bin.install "nb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardasevinc/netbird-cli/releases/download/v1.1.3/nb_1.1.3_linux_arm64.tar.gz"
      sha256 "12eea47bccb7280e424637c90b2c2f9ec73c02a9ef092bdab50e07b342f0e190"
      define_method(:install) do
        bin.install "nb"
      end
    end
  end

  test do
    system "#{bin}/nb", "version"
  end
end
